demo_job_1:
  tags:
    - ci
  script:
    - echo Hello World

stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - cd client
    - npm install
    - npm build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"
