image: docker

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node
  tags:
    - ci
  script:
    - echo "Start building App"
    - npm install --prefix ./client
    - npm install --prefix ./server
    - CI=false npm run build --prefix ./client
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 week
    paths:
      - ./client/build
      - ./client/node_modules/
      - ./server/node_modules/

test:
  stage: test
  image: node
  tags:
    - ci
  script:
    - echo "Testing React App"
    - CI=true npm test --prefix ./client
    - echo "Testing NodeJS App"
    - CI=true npm test --prefix ./server
    - echo "Test successfully!"

deploy:
  stage: deploy
  only:
    - main
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d --build
  environment: main
  when: manual
