demo_job_1:
  tags:
    - ci
  script:
    - echo Hello World

stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - npm install --prefix ./client
    - CI=false npm run build --prefix ./client
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - ./client/build
      - ./client/node_modules/

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - CI=true npm test --prefix ./client
    - echo "Test successfully!"
