version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "booklog-node"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "booklog-react"
    ports:
      - "3000:3000"
    links:
      - "backend"
